### ISSUE TITLE
Helm chart broken.   Incorrect indentation at line 139

### ISSUE THREAD

**Issue by hybrismerch** [Peripli/service-broker-proxy-k8s#127]
Hi there, currently getting 
Error: looks like "https://peripli.github.io" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 138: did not find expected key
upon investigation https://peripli.github.io/index.yaml line 139 should have an additional two spaces?
Rob, UK

**Comment by eyalnathan** [comment]
Hi Rob, the issue should be gone now. Thanks!

**Comment by hybrismerch** [comment]
Yes, resolved.  thanks.
