### ISSUE TITLE
Adopt latest proxy framework

### ISSUE THREAD

**Issue by KirilKabakchiev** [Peripli/service-broker-proxy-k8s#20]
There are some non-compatible changes in the proxy framework (mainly regarding configuration and environment loading).

The latest version of the proxy framework should be adopted by the K8S proxy.
For a reference, the CF proxy adoption may be used: https://github.com/Peripli/service-broker-proxy-cf/pull/11

**Comment by georgifarashev** [comment]
Fixed by https://github.com/Peripli/service-broker-proxy-k8s/pull/22 and https://github.com/Peripli/service-broker-proxy-k8s/pull/26
