### ISSUE TITLE
Reuse helm charts approach from Service Manager

### ISSUE THREAD

**Issue by KirilKabakchiev** [Peripli/service-broker-proxy-k8s#21]
There are similar steps in the helm installatiation for the proxy and the service manager and currently they are done differently. It would be better to unify (use the same approach) on both places.

One example would be that service manager uses a configmap to setup the "application.yml" (https://github.com/Peripli/service-manager/blob/master/deployment/k8s/charts/service-manager/templates/sm02-configmap.yaml) and the location/name/format can be passed in as cmd flags (https://github.com/Peripli/service-manager/blob/master/deployment/k8s/charts/service-manager/templates/sm03-deployment.yaml#L40 ) whereas in the K8S proxy we use env variables to achieve the same thing.

As part of this issue the approach used for both helm charts should be unified.

**Comment by georgifarashev** [comment]
Fixed by https://github.com/Peripli/service-broker-proxy-k8s/pull/22
