### ISSUE TITLE
bad version number

### ISSUE THREAD

**Issue by obeyler** [Peripli/service-broker-proxy-k8s#35]
in file charts/service-broker-proxy-k8s/Chart.yaml
version set 0.0.0

**Comment by georgifarashev** [comment]
The idea here was that when we create a new release in GitHub the chart is packaged with this specific version automatically and it is uploaded to releases. See for version 0.1.1 https://github.com/Peripli/service-broker-proxy-k8s/releases/tag/v0.1.1 
We could use the latest released version in master but we decided to leave it 0.0.0 which is ok to install with helm.

**Comment by obeyler** [comment]
I see that for tag 0.1.1 the version is bad :
![image](https://user-images.githubusercontent.com/23224162/47584210-e4dff780-d959-11e8-86ea-62295aca87bd.png)
If you don't change the version , the helm chart version will be bad and stick to 0.0.0 so you cannot upgrade your chart deployment. It's a very bad idea to stay 0.0.0 for helm chart.
Note that the helm chart version is frequently not same as application release version as development of application as not the main velocity as the helm chart.

**Comment by georgifarashev** [comment]
I meant in the uploaded chart to releases the version is changed https://github.com/Peripli/service-broker-proxy-k8s/releases/download/v0.1.1/service-broker-proxy-k8s-0.1.1.tgz But I agree it is strange and we should fix it.
