### ISSUE TITLE
Fix a version that refer for k8s.io/apimachinery

### ISSUE THREAD

**Issue by dzahariev** [Peripli/service-broker-proxy-k8s#39]
https://github.com/Peripli/service-broker-proxy-k8s/blob/master/Gopkg.lock#L666

The proposal is not to refer "master" branch (as it can bring instabilities) but to refer a stable version. For instance version 1.10.9.

**Comment by georgifarashev** [comment]
Fixed with https://github.com/Peripli/service-broker-proxy-k8s/pull/56
