### ISSUE TITLE
Add securityContext

### ISSUE THREAD

**Issue by obeyler** [Peripli/service-broker-proxy-k8s#43]
If you want to be deployed in a K8S with PodSecurityPolicy enabled with RunAsNonRoot, you must add a securityContext in the spec of your container.
If you want I can propose a PR for That

**Comment by KirilKabakchiev** [comment]
Sure, that would be great. If you'd like you could also add that to the service manager k8s deployment as well so that we are consistent.

**Comment by obeyler** [comment]
PR done: https://github.com/Peripli/service-broker-proxy-k8s/pull/44
