### ISSUE TITLE
Pod instantly errors after install

### ISSUE THREAD

**Issue by mr-flannery** [Peripli/service-broker-proxy-k8s#67]
I already successfully installed this chart last week. After restarting my cluster today (hibernation), I noticed that the service-broker-proxy was in status `CrashLoopBackOff`. Since I found no straight-forward way to restart a pod (not sure if this is even intended in k8s), I ran `helm del --purge` on my broker proxy and reinstalled. Unfortunately, this didn't help. When looking at the pods immediately afterwards, it's in status `Error`, and then it again changes to status `CrashLoopBackOff`.
I tried getting logs from the pod, but the `logs` command returns nothing, so it seems like no logs are written.

Is there something I can do here? If you need more information, let me know! Thanks!

**Comment by mr-flannery** [comment]
I'm installing from `master`. For Service Manager I don't select a version, I just subscribe to the app on cf. So I have no idea what version it gives me.

**Comment by dotchev** [comment]
Recent versions introduced some incompatible changes, so try with broker proxy v0.3.0.

**Comment by mr-flannery** [comment]
Thanks for the feedback! adding `--set image.tag=v0.3.0` fixed it for me.
